### ISSUE TITLE
About the pytorch version

### ISSUE THREAD

**Issue by junzhuang-code** [danielzuegner/nettack#11]
Currently, Nettack implements the attack on CPU. It will be too slower when n_influencer is too large.

Is any version of re-implementation available based on Pytorch?

Any hints would be helpful. Thanks in advance.

**Comment by danielzuegner** [comment]
Hi, yes the attack is implemented on CPU via just-in-time compilation (numba). So far I know of no efficient and vectorized implementation of the attack, which could be performed on CPU.
