### ISSUE TITLE
Question about surrogate model

### ISSUE THREAD

**Issue by jujulili888** [danielzuegner/nettack#15]
Hi Daniel,
Sorry to bother you. After reading your code, I have a question about the type of the attack. Do the parameters of the surrogate model continue to be updated like training process during an attack? Is that actually a evasion attack?

**Comment by danielzuegner** [comment]
Hi,

The surrogate model's parameters are not changed during the attack. It's like an evasion attack on the surrogate model, but a poisoning attack on the actual downstream model, which is subsequently trained on the perturbed data.

Hope that helps, let me know if you have more questions.

Best,

Daniel

**Comment by jujulili888** [comment]
Thanks for your explanation! Now I got it!

**Comment by jujulili888** [comment]
> Hi,
> 
> The surrogate model's parameters are not changed during the attack. It's like an evasion attack on the surrogate model, but a poisoning attack on the actual downstream model, which is subsequently trained on the perturbed data.
> 
> Hope that helps, let me know if you have more questions.
> 
> Best,
> 
> Daniel

Thanks for your explanation! Now I got it!
