### ISSUE TITLE
No Features for polblogs?

### ISSUE THREAD

**Issue by farezaur** [danielzuegner/nettack#3]
It seems there is no feature matrix available at least for the uploaded polblogs dataset? How did you do the feature matrix(X_obs) computation in this case?

**Comment by danielzuegner** [comment]
Hi,

the Polblogs dataset does not come with node attributes. In this case, we set the attributes matrix to the NxN identity matrix. In this case we can think of a GCN as performing some kind of label propagation on the graph.

**Comment by farezaur** [comment]
Thanks for the clarification. Does that mean that you cant perform feature perturbation on polblogs dataset? Because changing identity matrix won't be an unnoticable perturbation. Did you guys do that experiment?

**Comment by danielzuegner** [comment]
You are correct, in this case we can't perform feature perturbations. In our experiments in the paper, we only performed structure perturbations in this case.
