### ISSUE TITLE
Regeneration of results from the paper

### ISSUE THREAD

**Issue by farezaur** [danielzuegner/nettack#4]
Hi,

Can you guys give any codes/procedures/parameters to regenerate the result on the paper for GCN/CLN/DW?

Thanks

**Comment by danielzuegner** [comment]
Hi,

right now I don't have the whole pipeline ready for publication as it's pretty specific for my setup. I hope the procedure we followed in generating the results is mostly clear from the descriptions in the paper -- if you have any questions there feel free to reply here or send me an e-mail.

The code for GCN is included in this repo. For CLN (https://github.com/trangptm/Column_networks) and DeepWalk (https://github.com/phanein/deepwalk) we used the code provided by the authors with the standard hyperparameters. Let me know in case anything is unclear there.

Best,
Daniel

**Comment by farezaur** [comment]
Thanks for the reply. So, for the GCN experiments you used the code for the surrogate model that exists in this repo? Not the code in the original GCN repo. Is that correct? Just want to make sure which one should I use. 

Thanks in advance
Reza

**Comment by danielzuegner** [comment]
Yes. But make sure to pass `with_relu=True` so that you don't use the linearized surrogate model.

**Comment by farezaur** [comment]
Hi, I can't seem to run the CLN from their github. And it seems they did not reply to the issues there as well. Can you tell me how did you run their code? It seems the version of keras, tensorflow, numpy etc has to be same as the authors for running the code.

**Comment by danielzuegner** [comment]
I have a "fixed" (but pretty brittle) version of the authors' implementation. I have uploaded it [here](
https://syncandshare.lrz.de/dl/fiRwwcidJZoSN6GG7RSEGujG/cln_author_implementation.zip). See "How to run.txt" on which package versions I used to get it to run.
